# ✈️ Airline Passenger Satisfaction Prediction

## 01. Data Understanding

This notebook focuses on understanding the Airline Passenger Satisfaction dataset before performing data cleaning, preprocessing, and Artificial Neural Network modeling.

In [1]:
# Step 1 : Importing the Libraries

import pandas as pd
import numpy as np

In [2]:
# Step 2 : Loading the Training Dataset

train_path = "../data/raw/train.csv"

train_df = pd.read_csv(train_path)

print("Training dataset loaded successfully.")

Training dataset loaded successfully.

In [3]:
# Step 3 : Loading the Test Dataset

test_path = "../data/raw/test.csv"

test_df = pd.read_csv(test_path)

print("Test dataset loaded successfully.")

Test dataset loaded successfully.

In [4]:
# Step 4 : Checking the Training Dataset Shape

print("Training Dataset Shape:", train_df.shape)

Training Dataset Shape: (103904, 25)

In [5]:
# Step 5 : Checking the Test Dataset Shape

print("Test Dataset Shape:", test_df.shape)

Test Dataset Shape: (25976, 25)

In [6]:
# Step 6 : Displaying the First Five Training Records

train_df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [7]:
# Step 7 : Displaying the First Five Test Records

test_df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

In [8]:
# Step 8 : Checking the Training Dataset Columns

print("Training Dataset Columns:\n")

for column in train_df.columns:
    print(column)

Training Dataset Columns:

Unnamed: 0
id
Gender
Customer Type
Age
Type of Travel
Class
Flight Distance
Inflight wifi service
Departure/Arrival time convenient
Ease of Online booking
Gate location
Food and drink
Online boarding
Seat comfort
Inflight entertainment
On-board service
Leg room service
Baggage handling
Checkin service
Inflight service
Cleanliness
Departure Delay in Minutes
Arrival Delay in Minutes
satisfaction

In [9]:
# Step 9 : Checking the Test Dataset Columns

print("Test Dataset Columns:\n")

for column in test_df.columns:
    print(column)

Test Dataset Columns:

Unnamed: 0
id
Gender
Customer Type
Age
Type of Travel
Class
Flight Distance
Inflight wifi service
Departure/Arrival time convenient
Ease of Online booking
Gate location
Food and drink
Online boarding
Seat comfort
Inflight entertainment
On-board service
Leg room service
Baggage handling
Checkin service
Inflight service
Cleanliness
Departure Delay in Minutes
Arrival Delay in Minutes
satisfaction

In [10]:
# Step 10 : Checking the Data Types

train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Unnamed: 0                         103904 non-null  int64
 1   id                                 103904 non-null  int64
 2   Gender                             103904 non-null  str
 3   Customer Type                      103904 non-null  str
 4   Age                                103904 non-null  int64
 5   Type of Travel                     103904 non-null  str
 6   Class                              103904 non-null  str
 7   Flight Distance                    103904 non-null  int64
 8   Inflight wifi service              103904 non-null  int64
 9   Departure/Arrival time convenient  103904 non-null  int64
 10  Ease of Online booking             103904 non-null  int64
 11  Gate location                      103904 non-null  int64
 12  Food and drink                     103904 non-null  int64
 13  Online boarding                    103904 non-null  int64
 14  Seat comfort                       103904 non-null  int64
 15  Inflight entertainment             103904 non-null  int64
 16  On-board service                   103904 non-null  int64
 17  Leg room service                   103904 non-null  int64
 18  Baggage handling                   103904 non-null  int64
 19  Checkin service                    103904 non-null  int64
 20  Inflight service                   103904 non-null  int64
 21  Cleanliness                        103904 non-null  int64
 22  Departure Delay in Minutes         103904 non-null  int64
 23  Arrival Delay in Minutes           103594 non-null  float64
 24  satisfaction                       103904 non-null  str
dtypes: float64(1), int64(19), str(5)
memory usage: 25.5 MB

In [11]:
# Step 11 : Checking Test Dataset Data Types

test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   id                                 25976 non-null  int64
 2   Gender                             25976 non-null  str
 3   Customer Type                      25976 non-null  str
 4   Age                                25976 non-null  int64
 5   Type of Travel                     25976 non-null  str
 6   Class                              25976 non-null  str
 7   Flight Distance                    25976 non-null  int64
 8   Inflight wifi service              25976 non-null  int64
 9   Departure/Arrival time convenient  25976 non-null  int64
 10  Ease of Online booking             25976 non-null  int64
 11  Gate location                      25976 non-null  int64
 12  Food and drink                     25976 non-null  int64
 13  Online boarding                    25976 non-null  int64
 14  Seat comfort                       25976 non-null  int64
 15  Inflight entertainment             25976 non-null  int64
 16  On-board service                   25976 non-null  int64
 17  Leg room service                   25976 non-null  int64
 18  Baggage handling                   25976 non-null  int64
 19  Checkin service                    25976 non-null  int64
 20  Inflight service                   25976 non-null  int64
 21  Cleanliness                        25976 non-null  int64
 22  Departure Delay in Minutes         25976 non-null  int64
 23  Arrival Delay in Minutes           25893 non-null  float64
 24  satisfaction                       25976 non-null  str
dtypes: float64(1), int64(19), str(5)
memory usage: 6.4 MB

In [12]:
# Step 12 : Checking Missing Values in Training Data

missing_train = train_df.isnull().sum()

print("Missing Values in Training Dataset:\n")
print(missing_train)

Missing Values in Training Dataset:

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64

In [13]:
# Step 13 : Checking Missing Values in Test Data

missing_test = test_df.isnull().sum()

print("Missing Values in Test Dataset:\n")
print(missing_test)

Missing Values in Test Dataset:

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [14]:
# Step 14 : Checking Missing Value Percentage

missing_percentage = (
    train_df.isnull().sum() / len(train_df)
) * 100

missing_percentage = missing_percentage.sort_values(ascending=False)

print("Missing Value Percentage:\n")
print(missing_percentage)

Missing Value Percentage:

Arrival Delay in Minutes             0.298352
id                                   0.000000
Gender                               0.000000
Customer Type                        0.000000
Age                                  0.000000
Type of Travel                       0.000000
Class                                0.000000
Flight Distance                      0.000000
Unnamed: 0                           0.000000
Inflight wifi service                0.000000
Departure/Arrival time convenient    0.000000
Gate location                        0.000000
Ease of Online booking               0.000000
Online boarding                      0.000000
Seat comfort                         0.000000
Inflight entertainment               0.000000
Food and drink                       0.000000
On-board service                     0.000000
Leg room service                     0.000000
Checkin service                      0.000000
Baggage handling                     0.000000
Inflight service                     0.000000
Cleanliness                          0.000000
Departure Delay in Minutes           0.000000
satisfaction                         0.000000
dtype: float64

In [15]:
# Step 15 : Checking Duplicate Records

duplicate_count = train_df.duplicated().sum()

print("Number of Duplicate Records:", duplicate_count)

Number of Duplicate Records: 0

In [16]:
# Step 16 : Checking Test Dataset Duplicates

duplicate_test_count = test_df.duplicated().sum()

print("Number of Duplicate Records in Test Dataset:", duplicate_test_count)

Number of Duplicate Records in Test Dataset: 0

In [17]:
# Step 17 : Generating Statistical Summary

train_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,103904.0,NaN,NaN,NaN,51951.5,29994.645522,0.0,25975.75,51951.5,77927.25,103903.0
id,103904.0,NaN,NaN,NaN,64924.210502,37463.812252,1.0,32533.75,64856.5,97368.25,129880.0
Gender,103904,2,Female,52727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Type,103904,2,Loyal Customer,84923,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,103904.0,NaN,NaN,NaN,39.379706,15.114964,7.0,27.0,40.0,51.0,85.0
Type of Travel,103904,2,Business travel,71655,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Class,103904,3,Business,49665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Flight Distance,103904.0,NaN,NaN,NaN,1189.448375,997.147281,31.0,414.0,843.0,1743.0,4983.0
Inflight wifi service,103904.0,NaN,NaN,NaN,2.729683,1.327829,0.0,2.0,3.0,4.0,5.0
Departure/Arrival time convenient,103904.0,NaN,NaN,NaN,3.060296,1.525075,0.0,2.0,3.0,4.0,5.0
Ease of Online booking,103904.0,NaN,NaN,NaN,2.756901,1.398929,0.0,2.0,3.0,4.0,5.0
Gate location,103904.0,NaN,NaN,NaN,2.976883,1.277621,0.0,2.0,3.0,4.0,5.0
Food and drink,103904.0,NaN,NaN,NaN,3.202129,1.329533,0.0,2.0,3.0,4.0,5.0
Online boarding,103904.0,NaN,NaN,NaN,3.250375,1.349509,0.0,2.0,3.0,4.0,5.0
Seat comfort,103904.0,NaN,NaN,NaN,3.439396,1.319088,0.0,2.0,4.0,5.0,5.0
Inflight entertainment,103904.0,NaN,NaN,NaN,3.358158,1.332991,0.0,2.0,4.0,4.0,5.0
On-board service,103904.0,NaN,NaN,NaN,3.382363,1.288354,0.0,2.0,4.0,4.0,5.0
Leg room service,103904.0,NaN,NaN,NaN,3.351055,1.315605,0.0,2.0,4.0,4.0,5.0
Baggage handling,103904.0,NaN,NaN,NaN,3.631833,1.180903,1.0,3.0,4.0,5.0,5.0
Checkin service,103904.0,NaN,NaN,NaN,3.30429,1.265396,0.0,3.0,3.0,4.0,5.0
Inflight service,103904.0,NaN,NaN,NaN,3.640428,1.175663,0.0,3.0,4.0,5.0,5.0
Cleanliness,103904.0,NaN,NaN,NaN,3.286351,1.312273,0.0,2.0,3.0,4.0,5.0
Departure Delay in Minutes,103904.0,NaN,NaN,NaN,14.815618,38.230901,0.0,0.0,0.0,12.0,1592.0
Arrival Delay in Minutes,103594.0,NaN,NaN,NaN,15.178678,38.698682,0.0,0.0,0.0,13.0,1584.0
satisfaction,103904,2,neutral or dissatisfied,58879,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Step 18 : Checking Unique Values

for column in train_df.columns:
    print(f"\nColumn: {column}")
    print("Number of Unique Values:", train_df[column].nunique())

Column: Unnamed: 0
Number of Unique Values: 103904

Column: id
Number of Unique Values: 103904

Column: Gender
Number of Unique Values: 2

Column: Customer Type
Number of Unique Values: 2

Column: Age
Number of Unique Values: 75

Column: Type of Travel
Number of Unique Values: 2

Column: Class
Number of Unique Values: 3

Column: Flight Distance
Number of Unique Values: 3802

Column: Inflight wifi service
Number of Unique Values: 6

Column: Departure/Arrival time convenient
Number of Unique Values: 6

Column: Ease of Online booking
Number of Unique Values: 6

Column: Gate location
Number of Unique Values: 6

Column: Food and drink
Number of Unique Values: 6

Column: Online boarding
Number of Unique Values: 6

Column: Seat comfort
Number of Unique Values: 6

Column: Inflight entertainment
Number of Unique Values: 6

Column: On-board service
Number of Unique Values: 6

Column: Leg room service
Number of Unique Values: 6

Column: Baggage handling
Number of Unique Values: 5

Column: Checkin service
Number of Unique Values: 6

Column: Inflight service
Number of Unique Values: 6

Column: Cleanliness
Number of Unique Values: 6

Column: Departure Delay in Minutes
Number of Unique Values: 446

Column: Arrival Delay in Minutes
Number of Unique Values: 455

Column: satisfaction
Number of Unique Values: 2

In [19]:
# Step 19 : Displaying Sample Unique Values

for column in train_df.columns:
    print(f"\n{'=' * 60}")
    print(f"Column: {column}")
    print(train_df[column].unique()[:20])

============================================================
Column: Unnamed: 0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

============================================================
Column: id
[ 70172   5047 110028  24026 119299 111157  82113  96462  79485  65725
  34991  51412  98628  83502  95789 100580  71142 127461  70354  66246]

============================================================
Column: Gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

============================================================
Column: Customer Type
<ArrowStringArray>
['Loyal Customer', 'disloyal Customer']
Length: 2, dtype: str

============================================================
Column: Age
[13 25 26 61 47 52 41 20 24 12 53 33 45 38  9 17 43 58 23 57]

============================================================
Column: Type of Travel
<ArrowStringArray>
['Personal Travel', 'Business travel']
Length: 2, dtype: str

============================================================
Column: Class
<ArrowStringArray>
['Eco Plus', 'Business', 'Eco']
Length: 3, dtype: str

============================================================
Column: Flight Distance
[ 460  235 1142  562  214 1180 1276 2035  853 1061 1182  308  834  946
  453  486 2123 2075 2486 1174]

============================================================
Column: Inflight wifi service
[3 2 4 1 5 0]

============================================================
Column: Departure/Arrival time convenient
[4 2 5 3 1 0]

============================================================
Column: Ease of Online booking
[3 2 5 4 1 0]

============================================================
Column: Gate location
[1 3 2 5 4 0]

============================================================
Column: Food and drink
[5 1 2 4 3 0]

============================================================
Column: Online boarding
[3 5 2 1 4 0]

============================================================
Column: Seat comfort
[5 1 2 3 4 0]

============================================================
Column: Inflight entertainment
[5 1 2 3 4 0]

============================================================
Column: On-board service
[4 1 2 3 5 0]

============================================================
Column: Leg room service
[3 5 4 2 1 0]

============================================================
Column: Baggage handling
[4 3 5 1 2]

============================================================
Column: Checkin service
[4 1 3 5 2 0]

============================================================
Column: Inflight service
[5 4 3 1 2 0]

============================================================
Column: Cleanliness
[5 1 2 3 4 0]

============================================================
Column: Departure Delay in Minutes
[ 25   1   0  11   9   4  28  43  49   7  17  52  54  27  18  19   3 109
  23   8]

============================================================
Column: Arrival Delay in Minutes
[ 18.   6.   0.   9.  23.   8.  35.  51.  10.   5.   4.  29.  44.  28.
  12. 120.  24.   1.  20.  31.]

============================================================
Column: satisfaction
<ArrowStringArray>
['neutral or dissatisfied', 'satisfied']
Length: 2, dtype: str

In [20]:
# Step 20 : Identifying Numerical Columns

numerical_columns = train_df.select_dtypes(
    include=np.number
).columns.tolist()

print("Numerical Columns:")
print(numerical_columns)

Numerical Columns:
['Unnamed: 0', 'id', 'Age', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes']

In [28]:
# Step 20 : Identifying the Target Variable

print("Column Names in the Training Dataset:\n")

for index, column in enumerate(train_df.columns, start=1):
    print(f"{index}. {column}")

Column Names in the Training Dataset:

1. Unnamed: 0
2. id
3. Gender
4. Customer Type
5. Age
6. Type of Travel
7. Class
8. Flight Distance
9. Inflight wifi service
10. Departure/Arrival time convenient
11. Ease of Online booking
12. Gate location
13. Food and drink
14. Online boarding
15. Seat comfort
16. Inflight entertainment
17. On-board service
18. Leg room service
19. Baggage handling
20. Checkin service
21. Inflight service
22. Cleanliness
23. Departure Delay in Minutes
24. Arrival Delay in Minutes
25. satisfaction

In [21]:
# Step 21 : Identifying Categorical Columns

categorical_columns = train_df.select_dtypes(
    include="object"
).columns.tolist()

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction']

C:\Users\dhanu\AppData\Local\Temp\ipykernel_48568\2580530148.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = train_df.select_dtypes(

In [29]:
# Step 21 : Inspecting the Target Variable

target_column = "satisfaction"

print("Target Column:", target_column)

print("\nTarget Value Counts:")
print(train_df[target_column].value_counts())

print("\nTarget Value Percentages:")
print(train_df[target_column].value_counts(normalize=True).mul(100).round(2))

Target Column: satisfaction

Target Value Counts:
satisfaction
neutral or dissatisfied    58879
satisfied                  45025
Name: count, dtype: int64

Target Value Percentages:
satisfaction
neutral or dissatisfied    56.67
satisfied                  43.33
Name: proportion, dtype: float64

In [22]:
# Step 22 : Checking Numerical Statistics

train_df[numerical_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,103904.0,51951.500000,29994.645522,0.0,25975.75,51951.5,77927.25,103903.0
id,103904.0,64924.210502,37463.812252,1.0,32533.75,64856.5,97368.25,129880.0
Age,103904.0,39.379706,15.114964,7.0,27.00,40.0,51.00,85.0
Flight Distance,103904.0,1189.448375,997.147281,31.0,414.00,843.0,1743.00,4983.0
Inflight wifi service,103904.0,2.729683,1.327829,0.0,2.00,3.0,4.00,5.0
Departure/Arrival time convenient,103904.0,3.060296,1.525075,0.0,2.00,3.0,4.00,5.0
Ease of Online booking,103904.0,2.756901,1.398929,0.0,2.00,3.0,4.00,5.0
Gate location,103904.0,2.976883,1.277621,0.0,2.00,3.0,4.00,5.0
Food and drink,103904.0,3.202129,1.329533,0.0,2.00,3.0,4.00,5.0
Online boarding,103904.0,3.250375,1.349509,0.0,2.00,3.0,4.00,5.0
Seat comfort,103904.0,3.439396,1.319088,0.0,2.00,4.0,5.00,5.0
Inflight entertainment,103904.0,3.358158,1.332991,0.0,2.00,4.0,4.00,5.0
On-board service,103904.0,3.382363,1.288354,0.0,2.00,4.0,4.00,5.0
Leg room service,103904.0,3.351055,1.315605,0.0,2.00,4.0,4.00,5.0
Baggage handling,103904.0,3.631833,1.180903,1.0,3.00,4.0,5.00,5.0
Checkin service,103904.0,3.304290,1.265396,0.0,3.00,3.0,4.00,5.0
Inflight service,103904.0,3.640428,1.175663,0.0,3.00,4.0,5.00,5.0
Cleanliness,103904.0,3.286351,1.312273,0.0,2.00,3.0,4.00,5.0
Departure Delay in Minutes,103904.0,14.815618,38.230901,0.0,0.00,0.0,12.00,1592.0
Arrival Delay in Minutes,103594.0,15.178678,38.698682,0.0,0.00,0.0,13.00,1584.0

In [30]:
# Step 22 : Inspecting the Test Target Variable

print("Test Target Value Counts:")
print(test_df[target_column].value_counts())

print("\nTest Target Value Percentages:")
print(
    test_df[target_column]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Test Target Value Counts:
satisfaction
neutral or dissatisfied    14573
satisfied                  11403
Name: count, dtype: int64

Test Target Value Percentages:
satisfaction
neutral or dissatisfied    56.1
satisfied                  43.9
Name: proportion, dtype: float64

In [23]:
# Step 23 : Checking Target Column Candidates

print("All Training Dataset Columns:")
print(train_df.columns.tolist())

All Training Dataset Columns:
['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'satisfaction']

In [31]:
# Step 23 : Inspecting Categorical Features

for column in categorical_columns:
    print("=" * 70)
    print(f"Column: {column}")
    print(f"Number of Unique Values: {train_df[column].nunique()}")
    print("\nUnique Values:")
    print(train_df[column].unique())
    print()

======================================================================
Column: Gender
Number of Unique Values: 2

Unique Values:
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

======================================================================
Column: Customer Type
Number of Unique Values: 2

Unique Values:
<ArrowStringArray>
['Loyal Customer', 'disloyal Customer']
Length: 2, dtype: str

======================================================================
Column: Type of Travel
Number of Unique Values: 2

Unique Values:
<ArrowStringArray>
['Personal Travel', 'Business travel']
Length: 2, dtype: str

======================================================================
Column: Class
Number of Unique Values: 3

Unique Values:
<ArrowStringArray>
['Eco Plus', 'Business', 'Eco']
Length: 3, dtype: str

======================================================================
Column: satisfaction
Number of Unique Values: 2

Unique Values:
<ArrowStringArray>
['neutral or dissatisfied', 'satisfied']
Length: 2, dtype: str

In [24]:
# Step 24 : Checking the Last Column

last_column = train_df.columns[-1]

print("Last Column:", last_column)
print("\nValue Counts:")
print(train_df[last_column].value_counts())

Last Column: satisfaction

Value Counts:
satisfaction
neutral or dissatisfied    58879
satisfied                  45025
Name: count, dtype: int64

In [32]:
# Step 24 : Inspecting Numerical Feature Ranges

numerical_summary = train_df[numerical_columns].describe().T

numerical_summary[
    ["min", "max", "mean", "std"]
].round(2)

                                    min       max      mean       std
Unnamed: 0                          0.0  103903.0  51951.50  29994.65
id                                  1.0  129880.0  64924.21  37463.81
Age                                 7.0      85.0     39.38     15.11
Flight Distance                    31.0    4983.0   1189.45    997.15
Inflight wifi service               0.0       5.0      2.73      1.33
Departure/Arrival time convenient   0.0       5.0      3.06      1.53
Ease of Online booking              0.0       5.0      2.76      1.40
Gate location                       0.0       5.0      2.98      1.28
Food and drink                      0.0       5.0      3.20      1.33
Online boarding                     0.0       5.0      3.25      1.35
Seat comfort                        0.0       5.0      3.44      1.32
Inflight entertainment              0.0       5.0      3.36      1.33
On-board service                    0.0       5.0      3.38      1.29
Leg room service                    0.0       5.0      3.35      1.32
Baggage handling                    1.0       5.0      3.63      1.18
Checkin service                     0.0       5.0      3.30      1.27
Inflight service                    0.0       5.0      3.64      1.18
Cleanliness                         0.0       5.0      3.29      1.31
Departure Delay in Minutes          0.0    1592.0     14.82     38.23
Arrival Delay in Minutes            0.0    1584.0     15.18     38.70

In [25]:
# Step 25 : Comparing Train and Test Columns

train_columns = set(train_df.columns)
test_columns = set(test_df.columns)

print("Columns present only in Training Dataset:")
print(train_columns - test_columns)

print("\nColumns present only in Test Dataset:")
print(test_columns - train_columns)

Columns present only in Training Dataset:
set()

Columns present only in Test Dataset:
set()

In [33]:
# Step 25 : Inspecting Identifier Columns

print("Unnamed: 0 - First 10 Values:")
print(train_df["Unnamed: 0"].head(10).tolist())

print("\nUnnamed: 0 - Last 10 Values:")
print(train_df["Unnamed: 0"].tail(10).tolist())

print("\nID - First 10 Values:")
print(train_df["id"].head(10).tolist())

print("\nID - Number of Unique Values:")
print(train_df["id"].nunique())

print("\nTraining Rows:")
print(len(train_df))

Unnamed: 0 - First 10 Values:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Unnamed: 0 - Last 10 Values:
[103894, 103895, 103896, 103897, 103898, 103899, 103900, 103901, 103902, 103903]

ID - First 10 Values:
[70172, 5047, 110028, 24026, 119299, 111157, 82113, 96462, 79485, 65725]

ID - Number of Unique Values:
103904

Training Rows:
103904

In [26]:
# Step 26 : Checking Data Leakage Candidates

print("Training Dataset Columns:\n")

for index, column in enumerate(train_df.columns, start=1):
    print(index, ":", column)

Training Dataset Columns:

1 : Unnamed: 0
2 : id
3 : Gender
4 : Customer Type
5 : Age
6 : Type of Travel
7 : Class
8 : Flight Distance
9 : Inflight wifi service
10 : Departure/Arrival time convenient
11 : Ease of Online booking
12 : Gate location
13 : Food and drink
14 : Online boarding
15 : Seat comfort
16 : Inflight entertainment
17 : On-board service
18 : Leg room service
19 : Baggage handling
20 : Checkin service
21 : Inflight service
22 : Cleanliness
23 : Departure Delay in Minutes
24 : Arrival Delay in Minutes
25 : satisfaction

In [34]:
# Step 26 : Detailed Missing Value Analysis

missing_summary = pd.DataFrame({
    "Missing Count": train_df.isnull().sum(),
    "Missing Percentage": (
        train_df.isnull().sum() / len(train_df) * 100
    ).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values(
    by="Missing Count",
    ascending=False
)

missing_summary

                          Missing Count  Missing Percentage
Arrival Delay in Minutes            310                 0.3

In [27]:
# Step 27 : Final Dataset Summary

print("=" * 70)
print("AIRLINE PASSENGER SATISFACTION DATASET SUMMARY")
print("=" * 70)

print("\nTraining Dataset Shape :", train_df.shape)
print("Test Dataset Shape     :", test_df.shape)

print("\nNumber of Training Columns :", len(train_df.columns))
print("Number of Test Columns     :", len(test_df.columns))

print("\nTraining Missing Values :", train_df.isnull().sum().sum())
print("Test Missing Values     :", test_df.isnull().sum().sum())

print("\nTraining Duplicate Rows :", train_df.duplicated().sum())
print("Test Duplicate Rows     :", test_df.duplicated().sum())

print("\nNumerical Features :", len(numerical_columns))
print("Categorical Features :", len(categorical_columns))

print("\nDataset understanding completed.")

======================================================================
AIRLINE PASSENGER SATISFACTION DATASET SUMMARY
======================================================================

Training Dataset Shape : (103904, 25)
Test Dataset Shape     : (25976, 25)

Number of Training Columns : 25
Number of Test Columns     : 25

Training Missing Values : 310
Test Missing Values     : 83

Training Duplicate Rows : 0
Test Duplicate Rows     : 0

Numerical Features : 20
Categorical Features : 5

Dataset understanding completed.

In [35]:
# Step 27 : Detailed Test Missing Value Analysis

missing_test_summary = pd.DataFrame({
    "Missing Count": test_df.isnull().sum(),
    "Missing Percentage": (
        test_df.isnull().sum() / len(test_df) * 100
    ).round(2)
})

missing_test_summary = missing_test_summary[
    missing_test_summary["Missing Count"] > 0
].sort_values(
    by="Missing Count",
    ascending=False
)

missing_test_summary

                          Missing Count  Missing Percentage
Arrival Delay in Minutes             83                0.32

In [36]:
# Step 28 : Duplicate Row Analysis

train_duplicates = train_df.duplicated().sum()
test_duplicates = test_df.duplicated().sum()

print("Training Dataset Duplicates:", train_duplicates)
print("Testing Dataset Duplicates:", test_duplicates)

Training Dataset Duplicates: 0
Testing Dataset Duplicates: 0

In [37]:
# Step 29 : Numerical Feature Distribution Summary

numerical_summary = train_df[numerical_columns].describe().T

numerical_summary

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,103904.0,51951.500000,29994.645522,0.0,25975.75,51951.5,77927.25,103903.0
id,103904.0,64924.210502,37463.812252,1.0,32533.75,64856.5,97368.25,129880.0
Age,103904.0,39.379706,15.114964,7.0,27.00,40.0,51.00,85.0
Flight Distance,103904.0,1189.448375,997.147281,31.0,414.00,843.0,1743.00,4983.0
Inflight wifi service,103904.0,2.729683,1.327829,0.0,2.00,3.0,4.00,5.0
Departure/Arrival time convenient,103904.0,3.060296,1.525075,0.0,2.00,3.0,4.00,5.0
Ease of Online booking,103904.0,2.756901,1.398929,0.0,2.00,3.0,4.00,5.0
Gate location,103904.0,2.976883,1.277621,0.0,2.00,3.0,4.00,5.0
Food and drink,103904.0,3.202129,1.329533,0.0,2.00,3.0,4.00,5.0
Online boarding,103904.0,3.250375,1.349509,0.0,2.00,3.0,4.00,5.0
Seat comfort,103904.0,3.439396,1.319088,0.0,2.00,4.0,5.00,5.0
Inflight entertainment,103904.0,3.358158,1.332991,0.0,2.00,4.0,4.00,5.0
On-board service,103904.0,3.382363,1.288354,0.0,2.00,4.0,4.00,5.0
Leg room service,103904.0,3.351055,1.315605,0.0,2.00,4.0,4.00,5.0
Baggage handling,103904.0,3.631833,1.180903,1.0,3.00,4.0,5.00,5.0
Checkin service,103904.0,3.304290,1.265396,0.0,3.00,3.0,4.00,5.0
Inflight service,103904.0,3.640428,1.175663,0.0,3.00,4.0,5.00,5.0
Cleanliness,103904.0,3.286351,1.312273,0.0,2.00,3.0,4.00,5.0
Departure Delay in Minutes,103904.0,14.815618,38.230901,0.0,0.00,0.0,12.00,1592.0
Arrival Delay in Minutes,103594.0,15.178678,38.698682,0.0,0.00,0.0,13.00,1584.0

In [38]:
# Step 30 : Categorical Feature Distribution

categorical_features = [
    "Gender",
    "Customer Type",
    "Type of Travel",
    "Class"
]

for column in categorical_features:
    print(f"\n{'=' * 60}")
    print(f"{column}")
    print(f"{'=' * 60}")
    print(train_df[column].value_counts())

============================================================
Gender
============================================================
Gender
Female    52727
Male      51177
Name: count, dtype: int64

============================================================
Customer Type
============================================================
Customer Type
Loyal Customer       84923
disloyal Customer    18981
Name: count, dtype: int64

============================================================
Type of Travel
============================================================
Type of Travel
Business travel    71655
Personal Travel    32249
Name: count, dtype: int64

============================================================
Class
============================================================
Class
Business    49665
Eco         46745
Eco Plus     7494
Name: count, dtype: int64

In [39]:
# Step 31 : Target Variable Distribution

target_distribution = train_df[target_column].value_counts()

print("Target Variable Distribution:")
print(target_distribution)

print("\nTarget Variable Percentage:")
print(
    (train_df[target_column].value_counts(normalize=True) * 100).round(2)
)

Target Variable Distribution:
satisfaction
neutral or dissatisfied    58879
satisfied                  45025
Name: count, dtype: int64

Target Variable Percentage:
satisfaction
neutral or dissatisfied    56.67
satisfied                  43.33
Name: proportion, dtype: float64

In [40]:
# Step 32 : Test Target Variable Distribution

test_target_distribution = test_df[target_column].value_counts()

print("Test Target Variable Distribution:")
print(test_target_distribution)

print("\nTest Target Variable Percentage:")
print(
    (test_df[target_column].value_counts(normalize=True) * 100).round(2)
)

Test Target Variable Distribution:
satisfaction
neutral or dissatisfied    14573
satisfied                  11403
Name: count, dtype: int64

Test Target Variable Percentage:
satisfaction
neutral or dissatisfied    56.1
satisfied                  43.9
Name: proportion, dtype: float64

In [41]:
# Step 33 : Numerical Features and Target Relationship

numerical_features_for_analysis = [
    column for column in numerical_columns
    if column not in ["Unnamed: 0", "id"]
]

for column in numerical_features_for_analysis:
    print(f"\n{'=' * 60}")
    print(f"{column}")
    print(f"{'=' * 60}")
    
    print(
        train_df.groupby(target_column)[column]
        .mean()
        .round(2)
    )

============================================================
Age
============================================================
satisfaction
neutral or dissatisfied    37.57
satisfied                  41.75
Name: Age, dtype: float64

============================================================
Flight Distance
============================================================
satisfaction
neutral or dissatisfied     928.92
satisfied                  1530.14
Name: Flight Distance, dtype: float64

============================================================
Inflight wifi service
============================================================
satisfaction
neutral or dissatisfied    2.40
satisfied                  3.16
Name: Inflight wifi service, dtype: float64

============================================================
Departure/Arrival time convenient
============================================================
satisfaction
neutral or dissatisfied    3.13
satisfied                  2.97
Name: Departure/Arrival time convenient, dtype: float64

============================================================
Ease of Online booking
============================================================
satisfaction
neutral or dissatisfied    2.55
satisfied                  3.03
Name: Ease of Online booking, dtype: float64

============================================================
Gate location
============================================================
satisfaction
neutral or dissatisfied    2.98
satisfied                  2.98
Name: Gate location, dtype: float64

============================================================
Food and drink
============================================================
satisfaction
neutral or dissatisfied    2.96
satisfied                  3.52
Name: Food and drink, dtype: float64

============================================================
Online boarding
============================================================
satisfaction
neutral or dissatisfied    2.66
satisfied                  4.03
Name: Online boarding, dtype: float64

============================================================
Seat comfort
============================================================
satisfaction
neutral or dissatisfied    3.04
satisfied                  3.97
Name: Seat comfort, dtype: float64

============================================================
Inflight entertainment
============================================================
satisfaction
neutral or dissatisfied    2.89
satisfied                  3.96
Name: Inflight entertainment, dtype: float64

============================================================
On-board service
============================================================
satisfaction
neutral or dissatisfied    3.02
satisfied                  3.86
Name: On-board service, dtype: float64

============================================================
Leg room service
============================================================
satisfaction
neutral or dissatisfied    2.99
satisfied                  3.82
Name: Leg room service, dtype: float64

============================================================
Baggage handling
============================================================
satisfaction
neutral or dissatisfied    3.38
satisfied                  3.97
Name: Baggage handling, dtype: float64

============================================================
Checkin service
============================================================
satisfaction
neutral or dissatisfied    3.04
satisfied                  3.65
Name: Checkin service, dtype: float64

============================================================
Inflight service
============================================================
satisfaction
neutral or dissatisfied    3.39
satisfied                  3.97
Name: Inflight service, dtype: float64

============================================================
Cleanliness
============================================================
satisfaction
neutral or dissatisfied    2.94
satisfied                  3.74
Name: Cleanliness, dtype: float64

============================================================
Departure Delay in Minutes
============================================================
satisfaction
neutral or dissatisfied    16.50
satisfied                  12.61
Name: Departure Delay in Minutes, dtype: float64

============================================================
Arrival Delay in Minutes
============================================================
satisfaction
neutral or dissatisfied    17.13
satisfied                  12.63
Name: Arrival Delay in Minutes, dtype: float64

In [42]:
# Step 34 : Categorical Features and Target Relationship

for column in categorical_features:
    print(f"\n{'=' * 60}")
    print(f"{column} vs {target_column}")
    print(f"{'=' * 60}")
    
    print(
        pd.crosstab(
            train_df[column],
            train_df[target_column],
            normalize="index"
        ).round(3)
    )

============================================================
Gender vs satisfaction
============================================================
satisfaction  neutral or dissatisfied  satisfied
Gender
Female                          0.573      0.427
Male                            0.561      0.439

============================================================
Customer Type vs satisfaction
============================================================
satisfaction       neutral or dissatisfied  satisfied
Customer Type
Loyal Customer                       0.523      0.477
disloyal Customer                    0.763      0.237

============================================================
Type of Travel vs satisfaction
============================================================
satisfaction     neutral or dissatisfied  satisfied
Type of Travel
Business travel                    0.417      0.583
Personal Travel                    0.898      0.102

============================================================
Class vs satisfaction
============================================================
satisfaction  neutral or dissatisfied  satisfied
Class
Business                        0.306      0.694
Eco                             0.814      0.186
Eco Plus                        0.754      0.246

In [43]:
# Step 35 : Feature Data Types

data_types_summary = pd.DataFrame({
    "Column": train_df.columns,
    "Data Type": train_df.dtypes.astype(str)
})

data_types_summary

                                                              Column Data Type
Unnamed: 0                                                Unnamed: 0     int64
id                                                                id     int64
Gender                                                        Gender       str
Customer Type                                          Customer Type       str
Age                                                              Age     int64
Type of Travel                                        Type of Travel       str
Class                                                          Class       str
Flight Distance                                      Flight Distance     int64
Inflight wifi service                          Inflight wifi service     int64
Departure/Arrival time convenient  Departure/Arrival time convenient     int64
Ease of Online booking                        Ease of Online booking     int64
Gate location                                          Gate location     int64
Food and drink                                        Food and drink     int64
Online boarding                                      Online boarding     int64
Seat comfort                                            Seat comfort     int64
Inflight entertainment                        Inflight entertainment     int64
On-board service                                    On-board service     int64
Leg room service                                    Leg room service     int64
Baggage handling                                    Baggage handling     int64
Checkin service                                      Checkin service     int64
Inflight service                                    Inflight service     int64
Cleanliness                                              Cleanliness     int64
Departure Delay in Minutes                Departure Delay in Minutes     int64
Arrival Delay in Minutes                    Arrival Delay in Minutes   float64
satisfaction                                            satisfaction       str

In [44]:
# Step 36 : Unique Value Count for All Features

unique_value_summary = pd.DataFrame({
    "Column": train_df.columns,
    "Unique Values": train_df.nunique()
}).sort_values(
    by="Unique Values",
    ascending=True
)

unique_value_summary

,Column,Unique Values
Customer Type,Customer Type,2
Gender,Gender,2
Type of Travel,Type of Travel,2
satisfaction,satisfaction,2
Class,Class,3
Baggage handling,Baggage handling,5
Gate location,Gate location,6
Ease of Online booking,Ease of Online booking,6
Food and drink,Food and drink,6
Online boarding,Online boarding,6
Seat comfort,Seat comfort,6
Inflight entertainment,Inflight entertainment,6
On-board service,On-board service,6
Leg room service,Leg room service,6
Departure/Arrival time convenient,Departure/Arrival time convenient,6
Inflight wifi service,Inflight wifi service,6
Inflight service,Inflight service,6
Cleanliness,Cleanliness,6
Checkin service,Checkin service,6
Age,Age,75
Departure Delay in Minutes,Departure Delay in Minutes,446
Arrival Delay in Minutes,Arrival Delay in Minutes,455
Flight Distance,Flight Distance,3802
id,id,103904
Unnamed: 0,Unnamed: 0,103904

In [45]:
# Step 37 : Potential Outlier Analysis

outlier_summary = []

for column in numerical_features_for_analysis:
    Q1 = train_df[column].quantile(0.25)
    Q3 = train_df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outlier_count = (
        (train_df[column] < lower_bound) |
        (train_df[column] > upper_bound)
    ).sum()
    
    outlier_summary.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": outlier_count,
        "Outlier Percentage": round(
            outlier_count / len(train_df) * 100, 2
        )
    })

outlier_summary = pd.DataFrame(outlier_summary)

outlier_summary.sort_values(
    by="Outlier Count",
    ascending=False
)

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier Percentage
16,Departure Delay in Minutes,0.0,12.0,12.0,-18.0,30.0,14529,13.98
17,Arrival Delay in Minutes,0.0,13.0,13.0,-19.5,32.5,13954,13.43
13,Checkin service,3.0,4.0,1.0,1.5,5.5,12891,12.41
1,Flight Distance,414.0,1743.0,1329.0,-1579.5,3736.5,2291,2.20
0,Age,27.0,51.0,24.0,-9.0,87.0,0,0.00
2,Inflight wifi service,2.0,4.0,2.0,-1.0,7.0,0,0.00
6,Food and drink,2.0,4.0,2.0,-1.0,7.0,0,0.00
3,Departure/Arrival time convenient,2.0,4.0,2.0,-1.0,7.0,0,0.00
4,Ease of Online booking,2.0,4.0,2.0,-1.0,7.0,0,0.00
5,Gate location,2.0,4.0,2.0,-1.0,7.0,0,0.00
9,Inflight entertainment,2.0,4.0,2.0,-1.0,7.0,0,0.00
8,Seat comfort,2.0,5.0,3.0,-2.5,9.5,0,0.00
7,Online boarding,2.0,4.0,2.0,-1.0,7.0,0,0.00
10,On-board service,2.0,4.0,2.0,-1.0,7.0,0,0.00
12,Baggage handling,3.0,5.0,2.0,0.0,8.0,0,0.00
11,Leg room service,2.0,4.0,2.0,-1.0,7.0,0,0.00
15,Cleanliness,2.0,4.0,2.0,-1.0,7.0,0,0.00
14,Inflight service,3.0,5.0,2.0,0.0,8.0,0,0.00

In [46]:
# Step 38 : Train-Test Feature Consistency

train_columns = set(train_df.columns)
test_columns = set(test_df.columns)

print("Columns only in Training Dataset:")
print(train_columns - test_columns)

print("\nColumns only in Testing Dataset:")
print(test_columns - train_columns)

print("\nSame Columns:", train_columns == test_columns)

Columns only in Training Dataset:
set()

Columns only in Testing Dataset:
set()

Same Columns: True

In [47]:
# Step 39 : Train-Test Numerical Range Comparison

range_comparison = pd.DataFrame({
    "Train Min": train_df[numerical_features_for_analysis].min(),
    "Train Max": train_df[numerical_features_for_analysis].max(),
    "Test Min": test_df[numerical_features_for_analysis].min(),
    "Test Max": test_df[numerical_features_for_analysis].max()
})

range_comparison

                                   Train Min  Train Max  Test Min  Test Max
Age                                      7.0       85.0       7.0      85.0
Flight Distance                         31.0     4983.0      31.0    4983.0
Inflight wifi service                    0.0        5.0       0.0       5.0
Departure/Arrival time convenient        0.0        5.0       0.0       5.0
Ease of Online booking                   0.0        5.0       0.0       5.0
Gate location                            0.0        5.0       1.0       5.0
Food and drink                           0.0        5.0       0.0       5.0
Online boarding                          0.0        5.0       0.0       5.0
Seat comfort                             0.0        5.0       1.0       5.0
Inflight entertainment                   0.0        5.0       0.0       5.0
On-board service                         0.0        5.0       0.0       5.0
Leg room service                         0.0        5.0       0.0       5.0
Baggage handling                         1.0        5.0       1.0       5.0
Checkin service                          0.0        5.0       1.0       5.0
Inflight service                         0.0        5.0       0.0       5.0
Cleanliness                              0.0        5.0       0.0       5.0
Departure Delay in Minutes               0.0     1592.0       0.0    1128.0
Arrival Delay in Minutes                 0.0     1584.0       0.0    1115.0

In [48]:
# Step 40 : Identify Non-Predictive Identifier Columns

identifier_columns = [
    "Unnamed: 0",
    "id"
]

print("Columns identified for removal during preprocessing:")
print(identifier_columns)

Columns identified for removal during preprocessing:
['Unnamed: 0', 'id']

In [49]:
# Step 41 : Final Data Understanding Summary

print("========== DATA UNDERSTANDING SUMMARY ==========")

print("\nTraining Shape:", train_df.shape)
print("Testing Shape:", test_df.shape)

print("\nTarget Column:", target_column)

print("\nNumerical Features:", len(numerical_features_for_analysis))
print("Categorical Features:", len(categorical_features))

print("\nTraining Missing Values:", train_df.isnull().sum().sum())
print("Testing Missing Values:", test_df.isnull().sum().sum())

print("\nTraining Duplicates:", train_df.duplicated().sum())
print("Testing Duplicates:", test_df.duplicated().sum())

print("\nIdentifier Columns:", identifier_columns)

print("\nTarget Distribution:")
print(train_df[target_column].value_counts())

========== DATA UNDERSTANDING SUMMARY ==========

Training Shape: (103904, 25)
Testing Shape: (25976, 25)

Target Column: satisfaction

Numerical Features: 18
Categorical Features: 4

Training Missing Values: 310
Testing Missing Values: 83

Training Duplicates: 0
Testing Duplicates: 0

Identifier Columns: ['Unnamed: 0', 'id']

Target Distribution:
satisfaction
neutral or dissatisfied    58879
satisfied                  45025
Name: count, dtype: int64